'use strict';
const $=id=>document.getElementById(id), previews=new Map();
let signedIn=false,poll,sessions=[],activeId=null,terminal=null,fit=null,socket=null,observer=null,home='';
const make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const bytes=text=>Uint8Array.from(atob(text),c=>c.charCodeAt(0));
const base64=data=>{let text='';for(const b of new Uint8Array(data))text+=String.fromCharCode(b);return btoa(text);};
function notice(text){$('status').textContent=text;}
async function api(path,body){const init={credentials:'same-origin',cache:'no-store'};if(body!==undefined){init.method='POST';init.headers={'Content-Type':'application/json'};init.body=JSON.stringify(body);}const r=await fetch(path,init);if(!r.ok){if(r.status===401&&!path.includes('login'))lock();throw Error(await r.text());}return r.headers.get('content-type')?.includes('application/json')?r.json():r.text();}
function closeView(){observer?.disconnect();observer=null;socket?.close();socket=null;terminal?.dispose();terminal=null;fit=null;}
function lock(){signedIn=false;clearInterval(poll);closeView();for(const value of previews.values())value.term.dispose();previews.clear();$('running-grid').replaceChildren();$('exited-grid').replaceChildren();$('workspace').hidden=true;$('login').hidden=false;}
function showGrid(){activeId=null;closeView();$('detail').hidden=true;$('overview').hidden=false;$('sidebar').hidden=true;refresh().catch(e=>notice(e.message));}
function duration(s){return `${Math.max(0,Math.round((s.ended||Date.now()/1000)-s.created))}s`;}
function terminalOptions(extra={}){return {cursorBlink:false,disableStdin:true,scrollback:2000,fontSize:14,theme:{background:'#101112',foreground:'#e7e5df'},linkHandler:{activate:()=>{}},...extra};}
function guardTerminal(t){t.parser.registerOscHandler(52,()=>true);}
async function updatePreview(session){const view=previews.get(session.id);if(!view||view.busy||(view.loaded&&session.state==='exited'))return;view.busy=true;try{const result=await api(`/api/output?id=${encodeURIComponent(session.id)}`);if(!previews.has(session.id))return;const output=bytes(result.output),end=result.offset+output.length;if(view.cursor<result.offset||view.cursor>end){view.term.reset();view.cursor=result.offset;}const start=Math.max(0,view.cursor-result.offset);if(start<output.length)view.term.write(output.slice(start));view.cursor=end;view.loaded=true;}catch(e){if(signedIn)notice(e.message);}finally{view.busy=false;}}
function renderSessions(){const known=new Set(sessions.map(s=>s.id));for(const [id,v]of previews){if(!known.has(id)){v.term.dispose();v.card.remove();previews.delete(id);}}let running=0,exited=0;for(const s of sessions){if(s.state==='running')running++;else exited++;let v=previews.get(s.id);if(!v){const card=make('button',undefined,'session-card');card.setAttribute('aria-label',`Open session ${s.name}`);const heading=make('div',s.name,'card-name'),surface=make('div',undefined,'preview'),meta=make('div',undefined,'card-meta');card.append(heading,surface,meta);card.addEventListener('click',()=>openSession(s.id));$(s.state==='running'?'running-grid':'exited-grid').append(card);const t=new Terminal(terminalOptions({cols:80,rows:12,fontSize:8,scrollback:40}));t.open(surface);guardTerminal(t);v={card,term:t,meta,cursor:0,loaded:false,busy:false,state:s.state};previews.set(s.id,v);}if(v.state!==s.state){v.state=s.state;v.loaded=false;}const parent=$(s.state==='running'?'running-grid':'exited-grid');if(v.card.parentElement!==parent)parent.append(v.card);v.meta.replaceChildren(make('div',`● ${s.state} · ${duration(s)}`,s.state==='running'?'running-dot':'exited-dot'),make('div',s.directory));if(!activeId)updatePreview(s);}
$('running-count').textContent=`(${running})`;$('exited-count').textContent=`(${exited})`;$('counts').textContent=`(${running})`;$('footer-count').textContent=`${running} running · ${exited} exited`;$('empty').hidden=sessions.length>0;$('clean').disabled=exited===0;
$('session-list').replaceChildren(...sessions.map(s=>{const row=make('button',undefined,'sidebar-row'+(s.id===activeId?' selected':''));row.append(make('span',`${s.state==='running'?'●':'○'} ${s.name}`),make('small',`${s.directory} · ${duration(s)}`));row.addEventListener('click',()=>openSession(s.id));return row;}));
if(activeId){const s=sessions.find(s=>s.id===activeId);if(!s){showGrid();return;}$('terminal-state').textContent=s.state.toUpperCase();$('terminal-stop').disabled=s.state!=='running';$('terminal-reconnect').hidden=s.state!=='running';$('exited-banner').hidden=s.state!=='exited';if(s.state==='exited'&&socket){socket.close();socket=null;}}}
async function refresh(){const data=await api('/api/status');sessions=data.sessions||[];home=data.home||home;$('expiry').textContent=data.teleport||'Unavailable';$('version').textContent=`v${data.version||''}`;const listeners=data.listeners||[];$('listener-count').textContent=listeners.filter(x=>x.listening).length;$('socket-count').textContent=listeners.reduce((n,x)=>n+x.sessions,0);$('sharing').textContent=data.sharing?.join(' · ')||'Local access only';renderSessions();}
async function unlock(){await refresh();signedIn=true;$('login').hidden=true;$('workspace').hidden=false;clearInterval(poll);poll=setInterval(()=>refresh().catch(e=>notice(e.message)),3000);showGrid();}
async function openSession(id){const session=sessions.find(s=>s.id===id);if(!session)return;closeView();activeId=id;$('overview').hidden=true;$('detail').hidden=false;$('sidebar').hidden=innerWidth<760;$('terminal-name').textContent=session.name;$('terminal-directory').textContent=session.directory;$('terminal-surface').replaceChildren();terminal=new Terminal(terminalOptions({cursorBlink:true,disableStdin:session.state!=='running',fontSize:Number($('font-size').value),screenReaderMode:true}));fit=new FitAddon.FitAddon();terminal.loadAddon(fit);terminal.open($('terminal-surface'));guardTerminal(terminal);const current=terminal;const send=value=>{if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(value));};const resize=()=>{if(terminal!==current)return;fit.fit();send({type:'resize',cols:Math.max(2,Math.min(500,current.cols)),rows:Math.max(2,Math.min(500,current.rows))});};observer=new ResizeObserver(resize);observer.observe($('terminal-surface'));fit.fit();renderSessions();
try{if(session.state==='exited'){const data=await api(`/api/output?id=${encodeURIComponent(id)}`);if(terminal===current)current.write(bytes(data.output));return;}const {ticket}=await api('/api/ticket',{id});if(terminal!==current)return;const ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/terminal`,['infraproxy',ticket]);socket=ws;ws.binaryType='arraybuffer';ws.onopen=()=>{if(terminal===current){resize();current.focus();notice('');}};ws.onmessage=e=>{if(terminal===current)current.write(new Uint8Array(e.data));};ws.onclose=()=>{if(terminal===current&&signedIn){notice('Browser detached. Use Reconnect to resume a running session.');refresh().catch(()=>{});}};ws.onerror=()=>{if(terminal===current)notice('Connection interrupted. Your session remains on the Mac.');};current.onData(data=>{if(terminal!==current)return;const chars=Array.from(data);for(let i=0;i<chars.length;i+=1024)send({type:'input',data:chars.slice(i,i+1024).join('')});});}catch(e){notice(e.message);}}
function newSession(kind='shell'){$('session-kind').value=kind;$('session-name').value=kind==='tmux'?'tmux session':'Terminal';$('session-directory').value=home;$('new-dialog').showModal();}
for(const id of ['new-terminal','empty-new','sidebar-new'])$(id).addEventListener('click',()=>newSession());$('back').addEventListener('click',showGrid);
$('new-form').addEventListener('submit',async e=>{e.preventDefault();try{const value=await api('/api/sessions',{name:$('session-name').value,directory:$('session-directory').value,kind:$('session-kind').value});$('new-dialog').close();await refresh();await openSession(value.id);}catch(error){notice(error.message);}});
$('terminal-reconnect').addEventListener('click',()=>openSession(activeId));$('terminal-stop').addEventListener('click',async()=>{try{await api('/api/stop',{id:activeId});await refresh();}catch(e){notice(e.message);}});$('toggle-sidebar').addEventListener('click',()=>{$('sidebar').hidden=!$('sidebar').hidden;});
$('show-exited').addEventListener('change',()=>{$('exited-grid').hidden=!$('show-exited').checked;});$('clean').addEventListener('click',()=>$('clean-dialog').showModal());$('confirm-clean').addEventListener('click',async()=>{try{await api('/api/clean',{});$('clean-dialog').close();await refresh();}catch(e){notice(e.message);}});
$('connections-button').addEventListener('click',()=>{$('connection-stats').hidden=!$('connection-stats').hidden;});$('settings-button').addEventListener('click',()=>$('settings-dialog').showModal());for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>$(b.dataset.close).close());
$('theme').value=localStorage.getItem('infravibe-theme')||'dark';document.body.classList.toggle('light',$('theme').value==='light');$('theme').addEventListener('change',()=>{document.body.classList.toggle('light',$('theme').value==='light');localStorage.setItem('infravibe-theme',$('theme').value);});$('font-size').value=localStorage.getItem('infravibe-font')||'14';$('font-size').addEventListener('input',()=>{localStorage.setItem('infravibe-font',$('font-size').value);if(terminal){terminal.options.fontSize=Number($('font-size').value);fit.fit();}});
$('tmux-button').addEventListener('click',async()=>{$('tmux-dialog').showModal();$('tmux-message').textContent='Discovering tmux sessions…';$('tmux-list').replaceChildren();try{const data=await api('/api/tmux',{});$('tmux-message').textContent=!data.available?'Host tmux attachment is unavailable in sandboxed sessions.':data.sessions.length?'Attach to an existing session.':'No tmux sessions. Create one to get started.';$('new-tmux').disabled=!data.available;for(const s of data.sessions){const row=make('div',undefined,'tmux-row'),button=make('button','Attach');row.append(make('span',`${s.name} · ${s.windows} windows`),button);button.addEventListener('click',async()=>{try{const value=await api('/api/sessions',{name:`tmux: ${s.name}`,kind:'tmux-attach',target:s.id,directory:home});$('tmux-dialog').close();await refresh();openSession(value.id);}catch(e){notice(e.message);}});$('tmux-list').append(row);}}catch(e){$('tmux-message').textContent=e.message;}});$('new-tmux').addEventListener('click',()=>{$('tmux-dialog').close();newSession('tmux');});
$('terminal-snapshot').addEventListener('click',()=>{if(!terminal)return;const canvas=document.createElement('canvas');canvas.width=terminal.cols*9+32;canvas.height=terminal.rows*18+32;const context=canvas.getContext('2d');context.fillStyle='#101112';context.fillRect(0,0,canvas.width,canvas.height);context.font='14px monospace';context.fillStyle='#e7e5df';for(let row=0;row<terminal.rows;row++){const line=terminal.buffer.active.getLine(terminal.buffer.active.viewportY+row);context.fillText(line?.translateToString()||'',16,30+row*18);}canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=make('a');a.href=url;a.download=`infravibe-session-${activeId}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});});
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const key=$('access-key').value;$('access-key').value='';try{await api('/api/login',{key});$('login-error').textContent='';await unlock();}catch(error){$('login-error').textContent=error.message;}});$('logout').addEventListener('click',async()=>{try{await api('/api/logout',{});}finally{lock();}});
async function browserKey(write){return new Promise((resolve,reject)=>{const request=indexedDB.open('infravibe-browser-key',1);request.onupgradeneeded=()=>request.result.createObjectStore('keys');request.onerror=()=>reject(Error('Browser key storage is unavailable.'));request.onsuccess=()=>{const db=request.result,tx=db.transaction('keys',write?'readwrite':'readonly'),store=tx.objectStore('keys');let result;const op=write?store.put(write,'identity'):store.get('identity');op.onsuccess=()=>{result=op.result;};tx.oncomplete=()=>{db.close();resolve(write||result);};tx.onerror=()=>{db.close();reject(Error('Browser key storage failed.'));};};});}
$('generate-key').addEventListener('click',async()=>{try{if(await browserKey())throw Error('This browser already has a key. Download its public key to approve it.');const pair=await crypto.subtle.generateKey('Ed25519',false,['sign','verify']);const raw=await crypto.subtle.exportKey('raw',pair.publicKey);await browserKey({privateKey:pair.privateKey,publicKey:base64(raw)});$('login-error').textContent='Key created in this browser. Download the public key and approve it in the Mac app.';}catch(e){$('login-error').textContent=e.message;}});
$('download-key').addEventListener('click',async()=>{try{const key=await browserKey();if(!key)throw Error('Create a browser key first.');const prefix=Uint8Array.from([0,0,0,11,...new TextEncoder().encode('ssh-ed25519'),0,0,0,32]),raw=bytes(key.publicKey),wire=new Uint8Array(51);wire.set(prefix);wire.set(raw,19);const url=URL.createObjectURL(new Blob([`ssh-ed25519 ${base64(wire)} infravibe-browser\n`],{type:'text/plain'})),a=make('a');a.href=url;a.download='infravibe-browser.pub';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){$('login-error').textContent=e.message;}});
$('ssh-login').addEventListener('click',async()=>{try{const key=await browserKey();if(!key)throw Error('Create and approve a browser key using Browser key management below.');const challenge=await api('/api/key-challenge',{});const signature=await crypto.subtle.sign('Ed25519',key.privateKey,bytes(challenge.challenge));await api('/api/key-login',{id:challenge.id,publicKey:key.publicKey,signature:base64(signature)});$('login-error').textContent='';await unlock();}catch(e){$('login-error').textContent=e.message;}});
(async()=>{const fragment=new URLSearchParams(location.hash.slice(1));let key=fragment.get('key');history.replaceState(null,'',location.pathname);try{if(key){await api('/api/login',{key});key=null;}await unlock();}catch(e){lock();}})();
